**Q1. Problem Statement:Feature Extraction**

Write  a  Python  program  that  reads  the demotext2.txt text  file  (provided  on LMS),   and   then the   following   are   the   tasks   that   are   to   be   taken   into consideration while constructing the solution.

1.Load the demotext2.txt text file into a variable and then close the file

2.Do sentence wise tokenization and list out generated tokens

3.Transform each token into a lower case

4.Do vectorization using TFID Vectorizer

5.Generate vector-matrix

1.Load the demotext2.txt text file into a variable and then close the file

In [ ]:
doc=open('demotext2.txt')
text=doc.read()
doc.close()
print(text)

He can even spout some sports trivia and Christmas carols and stuff like that.
We'd talk sports and stuff, and maybe have a beer.
The Admirable Crichton of his day, he was keen alike on field sports and the arts, the friend and admirer equally of Cecil Rhodes and of Rodin, a railway director and a yeomanry colonel.
But he was not brought forward by his father or prepared in any way for his future greatness, and lived in the country occupied with field sports, till after the institution of the second protectorate in 16J7 and the recognition of Oliver's right to name his successor.
Thankfully, he was too concerned with sports to get in any real trouble.
See Strutt, Sports and Pastimes, who also gives an illustration, "taken from a manuscriptal painting of the 9th century in the Cotton Library," representing "a Saxon chieftain, attended by his huntsman and a couple of hounds, pursuing the wild swine in a forest."
As they entered the yard, Carmen noticed Lori's little red sports car.
After a lengthy shower, Jenn exited and pulled on clean leggings, sports bra, and socks.
A park and sports ground at the western end of the town contains the pedestal for a statue of President Kruger.
There were crude medieval notions that fossils were " freaks " or " sports " of nature (lusus naturae), or that they represented failures of a creative force within the earth (a notion of Greek and Arabic origin), or that larger and smaller fossils represented the remains of races of giants or of pygmies (the mythical idea).

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

2.Do sentence wise tokenization and list out generated tokens

In [ ]:
sent_tokens=nltk.sent_tokenize(text)
display(sent_tokens)

['He can even spout some sports trivia and Christmas carols and stuff like that.',
 "We'd talk sports and stuff, and maybe have a beer.",
 'The Admirable Crichton of his day, he was keen alike on field sports and the arts, the friend and admirer equally of Cecil Rhodes and of Rodin, a railway director and a yeomanry colonel.',
 "But he was not brought forward by his father or prepared in any way for his future greatness, and lived in the country occupied with field sports, till after the institution of the second protectorate in 16J7 and the recognition of Oliver's right to name his successor.",
 'Thankfully, he was too concerned with sports to get in any real trouble.',
 'See Strutt, Sports and Pastimes, who also gives an illustration, "taken from a manuscriptal painting of the 9th century in the Cotton Library," representing "a Saxon chieftain, attended by his huntsman and a couple of hounds, pursuing the wild swine in a forest."',
 "As they entered the yard, Carmen noticed Lori's little red sports car.",
 'After a lengthy shower, Jenn exited and pulled on clean leggings, sports bra, and socks.',
 'A park and sports ground at the western end of the town contains the pedestal for a statue of President Kruger.',
 'There were crude medieval notions that fossils were " freaks " or " sports " of nature (lusus naturae), or that they represented failures of a creative force within the earth (a notion of Greek and Arabic origin), or that larger and smaller fossils represented the remains of races of giants or of pygmies (the mythical idea).']

3.Transform each token into a lower case

In [ ]:
s=set(w.lower() for w in sent_tokens)
s=list(s)
display(s)

['the admirable crichton of his day, he was keen alike on field sports and the arts, the friend and admirer equally of cecil rhodes and of rodin, a railway director and a yeomanry colonel.',
 "but he was not brought forward by his father or prepared in any way for his future greatness, and lived in the country occupied with field sports, till after the institution of the second protectorate in 16j7 and the recognition of oliver's right to name his successor.",
 'see strutt, sports and pastimes, who also gives an illustration, "taken from a manuscriptal painting of the 9th century in the cotton library," representing "a saxon chieftain, attended by his huntsman and a couple of hounds, pursuing the wild swine in a forest."',
 'a park and sports ground at the western end of the town contains the pedestal for a statue of president kruger.',
 'after a lengthy shower, jenn exited and pulled on clean leggings, sports bra, and socks.',
 'he can even spout some sports trivia and christmas carols and stuff like that.',
 "as they entered the yard, carmen noticed lori's little red sports car.",
 "we'd talk sports and stuff, and maybe have a beer.",
 'there were crude medieval notions that fossils were " freaks " or " sports " of nature (lusus naturae), or that they represented failures of a creative force within the earth (a notion of greek and arabic origin), or that larger and smaller fossils represented the remains of races of giants or of pygmies (the mythical idea).',
 'thankfully, he was too concerned with sports to get in any real trouble.']

4.Do vectorization using TFID Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf_vect=TfidfVectorizer(min_df=1,lowercase=True,stop_words='english')
tf_matrix=tf_vect.fit_transform(s)
tf_matrix.shape

(10, 124)

In [ ]:
print(tf_matrix)

  (0, 19)	0.24354521874367308
  (0, 123)	0.24354521874367308
  (0, 29)	0.24354521874367308
  (0, 90)	0.24354521874367308
  (0, 99)	0.24354521874367308
  (0, 97)	0.24354521874367308
  (0, 14)	0.24354521874367308
  (0, 33)	0.24354521874367308
  (0, 3)	0.24354521874367308
  (0, 43)	0.24354521874367308
  (0, 6)	0.24354521874367308
  (0, 105)	0.09004358647762914
  (0, 37)	0.2070356862180743
  (0, 4)	0.24354521874367308
  (0, 56)	0.24354521874367308
  (0, 28)	0.24354521874367308
  (0, 26)	0.24354521874367308
  (0, 2)	0.24354521874367308
  (1, 110)	0.2243972359725302
  (1, 98)	0.2243972359725302
  (1, 77)	0.2243972359725302
  (1, 92)	0.2243972359725302
  (1, 0)	0.2243972359725302
  (1, 85)	0.2243972359725302
  (1, 101)	0.2243972359725302
  :	:
  (8, 103)	0.17921062626016357
  (8, 58)	0.17921062626016357
  (8, 78)	0.17921062626016357
  (8, 5)	0.17921062626016357
  (8, 48)	0.17921062626016357
  (8, 74)	0.17921062626016357
  (8, 30)	0.17921062626016357
  (8, 38)	0.17921062626016357
  (8, 25)	0.17921062626016357
  (8, 35)	0.17921062626016357
  (8, 95)	0.35842125252032714
  (8, 71)	0.17921062626016357
  (8, 66)	0.17921062626016357
  (8, 72)	0.17921062626016357
  (8, 42)	0.17921062626016357
  (8, 41)	0.35842125252032714
  (8, 75)	0.17921062626016357
  (8, 69)	0.17921062626016357
  (8, 27)	0.17921062626016357
  (8, 105)	0.06625778821119362
  (9, 118)	0.49166959587950165
  (9, 91)	0.49166959587950165
  (9, 20)	0.49166959587950165
  (9, 114)	0.49166959587950165
  (9, 105)	0.1817801803023365

5.Generate vector-matrix

In [ ]:
import pandas as pd
tf_names=tf_vect.get_feature_names_out()
tf_df=pd.DataFrame(tf_matrix.toarray(),columns=tf_names)
tf_df

,16j7,9th,admirable,admirer,alike,arabic,arts,attended,beer,bra,...,thankfully,till,town,trivia,trouble,way,western,wild,yard,yeomanry
0,0.000000,0.000000,0.243545,0.243545,0.243545,0.000000,0.243545,0.000000,0.00000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.243545
1,0.224397,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.00000,0.224397,0.000000,0.000000,0.00000,0.224397,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.212541,0.000000,0.000000,0.000000,0.000000,0.000000,0.212541,0.00000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.212541,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.00000,0.000000,0.314088,0.000000,0.00000,0.000000,0.314088,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.33083,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.00000,0.000000,0.000000,0.413119,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.350571,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.50903,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.179211,0.000000,0.000000,0.00000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,...,0.49167,0.000000,0.000000,0.000000,0.49167,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import stopwords
def clean_text(text):
  text=word_tokenize(text)
  text="".join(text)
  text=[char for char in text if char not in string.punctuation]
  text=" ".join(text)
  text=[word for word in text.split if word.lower() not in stopwords.words('english')]
  return " ".join(text)